# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 23:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_filename', models.CharField(max_length=10)),
                ('original_name', models.CharField(max_length=25, unique=True)),
                ('country', models.CharField(max_length=2, unique=True)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text=b'Name in English', max_length=50)),
                ('name_base', models.CharField(help_text=b'Name in base language', max_length=50)),
                ('name_target', models.CharField(help_text=b'Name in target language', max_length=50)),
                ('slug', models.CharField(db_index=True, help_text=b'URL slug', max_length=50, unique=True)),
                ('icon', models.CharField(help_text=b'Icon filename', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text=b'Date added')),
                ('visible', models.BooleanField(default=False)),
                ('from_exported_file', models.BooleanField(default=False, help_text=b'Data set was generated from an exported file')),
                ('word_count', models.IntegerField(help_text=b'Number of words in the dataset')),
                ('pos', models.CharField(help_text=b'Part of Speech', max_length=20)),
                ('learners', models.IntegerField(default=0, help_text=b'Number of people learning this dataset')),
                ('simple_dataset', models.BooleanField(default=False, help_text=b'If true, then this dataset is designed to contain basic words only')),
                ('reversed_set', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataSetProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=0)),
                ('date_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_set_progress', to='core.DataSet')),
            ],
        ),
        migrations.CreateModel(
            name='DS2WP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds2wp_ds', to='core.DataSet')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=256)),
                ('data_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_report_data_set', to='core.DataSet')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=25, unique=True)),
                ('original_name', models.CharField(max_length=25, unique=True)),
                ('acronym', models.CharField(max_length=5, unique=True)),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('image_filename', models.CharField(max_length=30)),
                ('flag_filename', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LanguagePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('learners', models.IntegerField(default=0, help_text=b'Number of people learning')),
                ('base_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_language', to='core.Language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_language', to='core.Language')),
            ],
        ),
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('os', models.CharField(max_length=100, null=True)),
                ('device_key', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=100, null=True)),
                ('device', models.CharField(max_length=100, null=True)),
                ('display', models.CharField(max_length=100, null=True)),
                ('hardware', models.CharField(max_length=100, null=True)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('sdk', models.CharField(max_length=100, null=True)),
                ('language', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonsterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_name', models.CharField(max_length=30)),
                ('new_email', models.CharField(max_length=50)),
                ('secure_hash', models.CharField(max_length=250, unique=True)),
                ('api_login_hash', models.CharField(max_length=250, unique=True)),
                ('avatar', models.CharField(max_length=250)),
                ('datasets', models.IntegerField(default=0)),
                ('uri', models.CharField(db_index=True, max_length=150, unique=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('social_account', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[(b'M', b'Make'), (b'F', b'Female')], max_length=2, null=True)),
                ('location', models.CharField(default=b'', max_length=18, null=True)),
                ('country', models.CharField(default=b'', max_length=20)),
                ('www', models.CharField(default=b'', max_length=20)),
                ('about', models.CharField(default=b'', max_length=500)),
                ('base_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monster_user_base_language', to='core.BaseLanguage')),
                ('current_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monster_user_current_language', to='core.Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonsterUserGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(default=b'', max_length=20)),
                ('played', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('monster_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monster_user_game', to='core.MonsterUser')),
            ],
        ),
        migrations.CreateModel(
            name='OpenGameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('game_session_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('game_token', models.CharField(max_length=128, unique=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_game_session_dataset', to='core.DataSet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_game_session_user', to='core.MonsterUser')),
            ],
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('trend', models.IntegerField(default=0)),
                ('average', models.IntegerField(default=0)),
                ('datasets', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_pair', to='core.LanguagePair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_monster_user', to='core.MonsterUser')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mark', models.IntegerField(default=0)),
                ('game', models.CharField(max_length=30)),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_result_data_set', to='core.DataSet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_result_user', to='core.MonsterUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserWordPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.BooleanField(default=False)),
                ('learned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_word_pair_user', to='core.MonsterUser')),
            ],
        ),
        migrations.CreateModel(
            name='WordPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.TextField()),
                ('target', models.TextField()),
                ('english', models.TextField()),
                ('comments', models.TextField()),
                ('pos', models.TextField()),
                ('base_en', models.TextField()),
                ('target_en', models.TextField()),
                ('english_invalid', models.BooleanField(default=False)),
                ('from_english', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('index', models.IntegerField(default=0)),
                ('pop', models.IntegerField(default=0, help_text=b'Popularity')),
            ],
        ),
        migrations.AddField(
            model_name='userwordpair',
            name='word_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_word_pair_word_pair', to='core.WordPair'),
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_device_user', to='core.MonsterUser'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_report_user', to='core.MonsterUser'),
        ),
        migrations.AddField(
            model_name='ds2wp',
            name='wp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds2wp_wp', to='core.WordPair'),
        ),
        migrations.AddField(
            model_name='datasetprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_set_user', to='core.MonsterUser'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_pair', to='core.LanguagePair'),
        ),
        migrations.AddField(
            model_name='baselanguage',
            name='language',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='userwordpair',
            unique_together=set([('word_pair', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='userresult',
            unique_together=set([('data_set', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='progression',
            unique_together=set([('user', 'pair')]),
        ),
        migrations.AlterUniqueTogether(
            name='languagepair',
            unique_together=set([('base_language', 'target_language')]),
        ),
        migrations.AlterUniqueTogether(
            name='ds2wp',
            unique_together=set([('ds', 'wp')]),
        ),
    ]
