# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_wordpair_data_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpair',
            name='data_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_pair_data_set', to='core.DataSet'),
        ),
    ]
