# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_wordpair_data_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monsteruser',
            name='social_account',
        ),
    ]
