# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_monsteruser_social_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsteruser',
            name='social_account',
            field=models.BooleanField(default=False),
        ),
    ]
