# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_monsteruser_social_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='core.Language'),
        ),
    ]
