# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160315_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baselanguage',
            options={'verbose_name': 'BaseLanguage', 'verbose_name_plural': 'Base Languages'},
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'verbose_name': 'DataSet', 'verbose_name_plural': 'Data Sets'},
        ),
        migrations.AlterModelOptions(
            name='datasetprogress',
            options={'verbose_name': 'DataSetProgress', 'verbose_name_plural': 'Data Set Progress'},
        ),
        migrations.AlterModelOptions(
            name='ds2wp',
            options={'verbose_name': 'DS2WP', 'verbose_name_plural': 'DataSet to WordPair'},
        ),
        migrations.AlterModelOptions(
            name='errorreport',
            options={'verbose_name': 'ErrorReport', 'verbose_name_plural': 'Error Reports'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='languagepair',
            options={'verbose_name': 'Language Pair', 'verbose_name_plural': 'Language Pairs'},
        ),
        migrations.AlterModelOptions(
            name='mobiledevice',
            options={'verbose_name': 'MobileDevice', 'verbose_name_plural': 'Mobile Devices'},
        ),
        migrations.AlterModelOptions(
            name='monsteruser',
            options={'verbose_name': 'MonsterUser', 'verbose_name_plural': 'Monster Users'},
        ),
        migrations.AlterModelOptions(
            name='monsterusergame',
            options={'verbose_name': 'MonsterUserGame', 'verbose_name_plural': 'Monster User Games'},
        ),
        migrations.AlterModelOptions(
            name='opengamesession',
            options={'verbose_name': 'OpenGameSession', 'verbose_name_plural': 'Open Game Sessions'},
        ),
        migrations.AlterModelOptions(
            name='progression',
            options={'verbose_name': 'Progression', 'verbose_name_plural': 'Progressions'},
        ),
        migrations.AlterModelOptions(
            name='simpledataset',
            options={'verbose_name': 'SimpleDataset', 'verbose_name_plural': 'Simple Datasets'},
        ),
        migrations.AlterModelOptions(
            name='userresult',
            options={'verbose_name': 'UserResult', 'verbose_name_plural': 'User Results'},
        ),
        migrations.AlterModelOptions(
            name='userwordpair',
            options={'verbose_name': 'UserWordPair', 'verbose_name_plural': 'User Word Pairs'},
        ),
        migrations.AlterModelOptions(
            name='wordpair',
            options={'verbose_name': 'WordPair', 'verbose_name_plural': 'Word Pairs'},
        ),
    ]
