# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160315_2257'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresult',
            unique_together=set([]),
        ),
    ]
