# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160317_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='lang_pair',
            field=models.CharField(default=b'en_en', max_length=5),
        ),
        migrations.AddField(
            model_name='monsteruser',
            name='language',
            field=models.CharField(default=b'en_uk', max_length=5),
        ),
        migrations.AddField(
            model_name='progression',
            name='lang_pair',
            field=models.CharField(default=b'en_en', max_length=5),
        ),
    ]
