# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160423_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='lang_pair',
            field=models.CharField(choices=[(b'en_de', b'en_de'), (b'en_es', b'en_es'), (b'en_fr', b'en_fr'), (b'en_it', b'en_it'), (b'en_pl', b'en_pl'), (b'en_pt', b'en_pt'), (b'pl_de', b'pl_de'), (b'pl_en', b'pl_en'), (b'pl_es', b'pl_es'), (b'pl_fr', b'pl_fr'), (b'pl_it', b'pl_it'), (b'pl_pt', b'pl_pt')], default=b'en_en', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('slug', 'lang_pair')]),
        ),
    ]
