# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20160501_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monsteruser',
            name='base_language',
        ),
        migrations.RemoveField(
            model_name='monsteruser',
            name='current_language',
        ),
    ]
