# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20160502_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='lang_pair',
            field=models.CharField(choices=[(b'en_de', b'English -> German'), (b'en_en', b'English -> English'), (b'en_es', b'English -> Spanish'), (b'en_fr', b'English -> French'), (b'en_it', b'English -> Italian'), (b'en_pl', b'English -> Polish'), (b'en_pt', b'English -> Portuguese'), (b'pl_de', b'Polish -> German'), (b'pl_en', b'Polish -> English'), (b'pl_es', b'Polish -> Spanish'), (b'pl_fr', b'Polish -> French'), (b'pl_it', b'Polish -> Italian'), (b'pl_pl', b'Polish -> Polish'), (b'pl_pt', b'Polish -> Portuguese')], help_text=b'Language Pair', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='monsteruser',
            name='language',
            field=models.CharField(choices=[(b'en_au', 'English (AU)'), (b'en_ca', 'English (CA)'), (b'en_nz', 'English (NZ)'), (b'en_uk', 'English (UK)'), (b'en_us', 'English (US)'), (b'pl_pl', 'Polski')], help_text=b'Base Language', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='progression',
            name='lang_pair',
            field=models.CharField(choices=[(b'en_de', b'English -> German'), (b'en_es', b'English -> Spanish'), (b'en_fr', b'English -> French'), (b'en_it', b'English -> Italian'), (b'en_pl', b'English -> Polish'), (b'en_pt', b'English -> Portuguese'), (b'pl_de', b'Polish -> German'), (b'pl_en', b'Polish -> English'), (b'pl_es', b'Polish -> Spanish'), (b'pl_fr', b'Polish -> French'), (b'pl_it', b'Polish -> Italian'), (b'pl_pt', b'Polish -> Portuguese')], help_text=b'Language Pair', max_length=5, null=True),
        ),
    ]
