# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20160502_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_filename', models.CharField(max_length=10)),
                ('original_name', models.CharField(max_length=25, unique=True)),
                ('country', models.CharField(max_length=2, unique=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BaseLanguage',
                'verbose_name_plural': 'Base Languages',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=25, unique=True)),
                ('original_name', models.CharField(max_length=25, unique=True)),
                ('acronym', models.CharField(max_length=5, unique=True)),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('image_filename', models.CharField(max_length=30)),
                ('flag_filename', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='LanguagePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('learners', models.IntegerField(default=0, help_text=b'Number of people learning')),
                ('base_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_language', to='core.Language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_language', to='core.Language')),
            ],
            options={
                'verbose_name': 'Language Pair',
                'verbose_name_plural': 'Language Pairs',
            },
        ),
        migrations.AlterField(
            model_name='dataset',
            name='lang_pair',
            field=models.CharField(choices=[(b'en_de', b'English -> German'), (b'en_en', b'English -> English'), (b'en_es', b'English -> Spanish'), (b'en_fr', b'English -> French'), (b'en_it', b'English -> Italian'), (b'en_pl', b'English -> Polish'), (b'en_pt', b'English -> Portuguese'), (b'pl_de', b'Polish -> German'), (b'pl_en', b'Polish -> English'), (b'pl_es', b'Polish -> Spanish'), (b'pl_fr', b'Polish -> French'), (b'pl_it', b'Polish -> Italian'), (b'pl_pl', b'Polish -> Polish'), (b'pl_pt', b'Polish -> Portuguese')], default=b'en_en', help_text=b'Language Pair', max_length=5),
        ),
        migrations.AlterField(
            model_name='monsteruser',
            name='language',
            field=models.CharField(choices=[(b'en_au', 'English (AU)'), (b'en_ca', 'English (CA)'), (b'en_nz', 'English (NZ)'), (b'en_uk', 'English (UK)'), (b'en_us', 'English (US)'), (b'pl_pl', 'Polski')], default=b'en_uk', help_text=b'Base Language', max_length=5),
        ),
        migrations.AlterField(
            model_name='progression',
            name='lang_pair',
            field=models.CharField(choices=[(b'en_de', b'English -> German'), (b'en_es', b'English -> Spanish'), (b'en_fr', b'English -> French'), (b'en_it', b'English -> Italian'), (b'en_pl', b'English -> Polish'), (b'en_pt', b'English -> Portuguese'), (b'pl_de', b'Polish -> German'), (b'pl_en', b'Polish -> English'), (b'pl_es', b'Polish -> Spanish'), (b'pl_fr', b'Polish -> French'), (b'pl_it', b'Polish -> Italian'), (b'pl_pt', b'Polish -> Portuguese')], default=b'en_en', help_text=b'Language Pair', max_length=5),
        ),
        migrations.AddField(
            model_name='baselanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='core.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='languagepair',
            unique_together=set([('base_language', 'target_language')]),
        ),
    ]
