# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-20 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20160718_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsteruser',
            name='secure_hash',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
