# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-25 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_monsteruser_social_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorreport',
            name='data_set',
        ),
        migrations.RemoveField(
            model_name='errorreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='ErrorReport',
        ),
    ]
