# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-28 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_dataset_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opengamesession',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='opengamesession',
            name='user',
        ),
        migrations.DeleteModel(
            name='OpenGameSession',
        ),
    ]
