# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-17 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20160828_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsteruser',
            name='api_login_hash',
            field=models.CharField(db_index=True, max_length=250, null=True, unique=True),
        ),
    ]
