# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-14 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20160926_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpair',
            name='pos',
            field=models.CharField(choices=[(b'Noun', b'Noun'), (b'ProperNoun', b'ProperNoun'), (b'Verb', b'Verb'), (b'Adverb', b'Adverb'), (b'Adjective', b'Adjective')], default=b'A', help_text=b'Part of speech', max_length=50, null=True),
        ),
    ]
