# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20161214_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpair',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
