# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-09 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_wordpair_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('lang_pair', models.CharField(choices=[(b'en_de', b'English -> German'), (b'en_en', b'English -> English'), (b'en_es', b'English -> Spanish'), (b'en_fr', b'English -> French'), (b'en_it', b'English -> Italian'), (b'en_pl', b'English -> Polish'), (b'en_pt', b'English -> Portuguese'), (b'pl_de', b'Polish -> German'), (b'pl_en', b'Polish -> English'), (b'pl_es', b'Polish -> Spanish'), (b'pl_fr', b'Polish -> French'), (b'pl_it', b'Polish -> Italian'), (b'pl_pl', b'Polish -> Polish'), (b'pl_pt', b'Polish -> Portuguese')], db_index=True, help_text=b'Language Pair', max_length=5, null=True)),
                ('slug', models.CharField(help_text=b'URL slug', max_length=128)),
            ],
        ),
    ]
